export type PortalFeatureCatalogItem = {
  feature_key: string;
  label: string;
  area: string;
  route_path: string;
};

export const PORTAL_FEATURE_CATALOG: PortalFeatureCatalogItem[] = [
  { feature_key: "home", label: "Home", area: "Geral", route_path: "/home" },
  { feature_key: "institucional_visao_geral", label: "Institucional - Visao geral", area: "Institucional", route_path: "/institucional" },
  { feature_key: "institucional_organograma", label: "Institucional - Organograma", area: "Institucional", route_path: "/institucional/organograma" },
  { feature_key: "perfil_meus_dados", label: "Meu perfil - Meus dados", area: "Meu perfil", route_path: "/meu-perfil/meus-dados" },
  { feature_key: "perfil_chamados", label: "Meu perfil - Chamados", area: "Meu perfil", route_path: "/meu-perfil/chamados" },
  { feature_key: "perfil_projetos", label: "Meu perfil - Projetos", area: "Meu perfil", route_path: "/meu-perfil/projetos" },
  { feature_key: "perfil_nota_fiscal", label: "Meu perfil - Nota fiscal", area: "Meu perfil", route_path: "/meu-perfil/nota-fiscal" },
  { feature_key: "perfil_linha_tempo", label: "Meu perfil - Linha do tempo", area: "Meu perfil", route_path: "/meu-perfil/linha-do-tempo" },
  { feature_key: "perfil_feedbacks", label: "Meu perfil - Feedbacks", area: "Meu perfil", route_path: "/meu-perfil/feedback" },
  { feature_key: "perfil_pdi", label: "Meu perfil - PDI", area: "Meu perfil", route_path: "/meu-perfil/pdi" },
  { feature_key: "perfil_competencias", label: "Meu perfil - Competencias", area: "Meu perfil", route_path: "/meu-perfil/competencias" },
  { feature_key: "perfil_mapa_comportamental", label: "Meu perfil - Mapa comportamental", area: "Meu perfil", route_path: "/meu-perfil/mapa-comportamental" },
  { feature_key: "perfil_avaliacao", label: "Meu perfil - Avaliacao de desempenho", area: "Meu perfil", route_path: "/meu-perfil/avaliacao-desempenho" },
  { feature_key: "agenda_aniversariantes", label: "Agenda - Aniversariantes", area: "Agenda", route_path: "/agenda/aniversariantes" },
  { feature_key: "agenda_institucional", label: "Agenda - Agenda institucional", area: "Agenda", route_path: "/agenda/agenda-institucional" },
  { feature_key: "agenda_ausencias", label: "Agenda - Ausencias programadas", area: "Agenda", route_path: "/meu-perfil/ausencias-programadas" },
  { feature_key: "coordenador_painel", label: "Coordenador - Painel", area: "Coordenador", route_path: "/coordenador" },
  { feature_key: "coordenador_feedback", label: "Coordenador - Aplicar feedback", area: "Coordenador", route_path: "/coordenador/feedback" },
  { feature_key: "coordenador_projetos", label: "Coordenador - Projetos", area: "Coordenador", route_path: "/coordenador/projetos" },
  { feature_key: "gestor_painel", label: "Gestor - Painel", area: "Gestor", route_path: "/gestor" },
  { feature_key: "gestor_feedback", label: "Gestor - Aplicar feedback", area: "Gestor", route_path: "/gestor/feedback" },
  { feature_key: "gestor_projetos", label: "Gestor - Projetos", area: "Gestor", route_path: "/gestor/projetos" },
  { feature_key: "gestor_pagamentos_extras", label: "Gestor - Pagamentos extras", area: "Gestor", route_path: "/gestor/pagamentos-extras" },
  { feature_key: "gestor_ausencias", label: "Gestor - Ausencias", area: "Gestor", route_path: "/gestor/ausencias" },
  { feature_key: "financeiro_painel", label: "Financeiro - Painel", area: "Financeiro", route_path: "/financeiro" },
  { feature_key: "financeiro_custos_indiretos", label: "Financeiro - Custos indiretos", area: "Financeiro", route_path: "/financeiro/custos-indiretos" },
  { feature_key: "financeiro_solicitacoes", label: "Financeiro - Solicitacoes", area: "Financeiro", route_path: "/financeiro/solicitacoes" },
  { feature_key: "financeiro_notas_fiscais", label: "Financeiro - Notas fiscais", area: "Financeiro", route_path: "/financeiro/notas-fiscais" },
  { feature_key: "financeiro_remessas", label: "Financeiro - Remessas", area: "Financeiro", route_path: "/financeiro/remessas" },
  { feature_key: "metas", label: "Metas", area: "Metas", route_path: "/metas" },
  { feature_key: "pd_painel", label: "P&D - Painel", area: "P&D", route_path: "/p-d" },
  { feature_key: "pd_chamados", label: "P&D - Chamados", area: "P&D", route_path: "/p-d/chamados" },
  { feature_key: "pd_projetos", label: "P&D - Projetos", area: "P&D", route_path: "/p-d/projetos" },
  { feature_key: "ceo_aditivos", label: "CEO - Aprovar aditivos", area: "CEO", route_path: "/ceo/aditivos-contratuais" },
  { feature_key: "rh_painel", label: "RH - Painel", area: "RH", route_path: "/rh" },
  { feature_key: "rh_dashboard", label: "RH - Dashboard", area: "RH", route_path: "/rh/dashboard" },
  { feature_key: "rh_demografia", label: "RH - Demografia", area: "RH", route_path: "/rh/demografia" },
  { feature_key: "rh_solicitacoes", label: "RH - Solicitacoes", area: "RH", route_path: "/rh/solicitacoes" },
  { feature_key: "rh_colaboradores", label: "RH - Colaboradores", area: "RH", route_path: "/rh/colaboradores" },
  { feature_key: "rh_adicionar_colaborador", label: "RH - Adicionar colaborador", area: "RH", route_path: "/rh/adicionar-colaborador" },
  { feature_key: "rh_cargos", label: "RH - Inclusao cargos", area: "RH", route_path: "/rh/cargos" },
  { feature_key: "rh_institucional", label: "RH - Institucional", area: "RH", route_path: "/rh/institucional" },
  { feature_key: "rh_feedbacks", label: "RH - Governanca feedback", area: "RH", route_path: "/rh/feedbacks" },
  { feature_key: "rh_mapa_comportamental", label: "RH - Mapa comportamental", area: "RH", route_path: "/rh/mapa-comportamental" },
  { feature_key: "rh_ausencias", label: "RH - Ausencias", area: "RH", route_path: "/rh/ausencias" },
  { feature_key: "diretoria_acompanhamento", label: "Diretoria - Acompanhamento", area: "Diretoria", route_path: "/diretoria/projetos" },
  { feature_key: "diretoria_novo_projeto", label: "Diretoria - Novo projeto", area: "Diretoria", route_path: "/diretoria/projetos/novo" },
  { feature_key: "diretoria_medicoes", label: "Diretoria - Medicoes/Boletins", area: "Diretoria", route_path: "/diretoria/medicoes" },
  { feature_key: "diretoria_contratos", label: "Diretoria - Aditivos/Contratos", area: "Diretoria", route_path: "/diretoria/contratos" },
  { feature_key: "diretoria_clientes", label: "Diretoria - Clientes", area: "Diretoria", route_path: "/diretoria/clientes" },
  { feature_key: "admin_painel", label: "Admin - Painel", area: "Admin", route_path: "/admin" },
  { feature_key: "admin_empresas", label: "Admin - Cadastro de empresas", area: "Admin", route_path: "/admin/empresas" },
  { feature_key: "admin_sla", label: "Admin - Configuracao SLA", area: "Admin", route_path: "/admin/sla" },
  { feature_key: "admin_notificacoes", label: "Admin - Notificacoes", area: "Admin", route_path: "/admin/notificacoes" },
  { feature_key: "admin_funcionalidades", label: "Admin - Visibilidade", area: "Admin", route_path: "/admin/funcionalidades" },
  { feature_key: "admin_sessoes", label: "Admin - Sessoes", area: "Admin", route_path: "/admin/sessoes" },
  { feature_key: "admin_permissoes", label: "Admin - Permissoes", area: "Admin", route_path: "/admin/permissoes" },
];
